#%RAML 1.0 NamedExample
value:
-
  EmpId: 1
  EmpName: veena
  Email: veena.vangala@gmail.com
  age: 29
  city: Hyderabad
  project: ABC
  manager: Ragalatha
- 
  EmpId: 2
  EmpName: swapna
  Email: swapna@gmail.com
  age: 30
  city: Hyderbad
  project: ABC
  manager: Ragalatha
  